import React from 'react';

const DonationsPage: React.FC = () => {
  const donationAddress = '0x9870425079f7c82d734aabaf891c96a652d13c221067decb32d726d37409f438'; // 假设的捐赠地址
  const totalRevenue = 0; // 假设的总收益数据，实际可以从API拉取
  const donationLeaderboard = []; // 假设的数据，可以用API拉取

  return (
    <div className="container mx-auto p-6">
      <h1 className="text-3xl font-bold text-center mb-8">Donations & Revenue Sharing</h1>

      {/* 捐赠地址部分 */}
      <div className=" shadow-md rounded-lg p-6 mb-6">
        <h2 className="text-2xl font-bold mb-4">Donation Wallet Address</h2>
        <p className="text-gray-700 mb-4">
          Support the development of this project by donating to the following address:
        </p>
        <p className="bg-gray-100 p-2 rounded text-gray-900 font-mono">
          {donationAddress}
        </p>
      </div>

      {/* 收益展示部分 */}
      <div className=" shadow-md rounded-lg p-6 mb-6">
        <h2 className="text-2xl font-bold mb-4">Project Revenue</h2>
        <p className="text-gray-700 mb-4">
          The total revenue generated by the project so far:
        </p>
        <p className="text-3xl font-bold text-blue-600">${totalRevenue}</p>
        <p className="text-sm text-gray-600 mt-2">The revenue will be reinvested into Navi based on AI's suggestions, and shared with donors and developers.</p>
      </div>

      {/* 捐赠排行榜部分 */}
      <div className="bg-gray-800 shadow-md rounded-lg p-6 text-center">
        <h2 className="text-2xl font-bold mb-4">Donation Leaderboard</h2>
        <p className="text-gray-700 mb-4">See how much our community has contributed!</p>
        
        {/* 判断捐赠排行榜是否为空 */}
        {donationLeaderboard.length > 0 ? (
          <ul className="list-disc list-inside">
            {donationLeaderboard.map((donor, index) => (
              <li key={index} className="text-gray-700">
                {donor.name}: ${donor.amount}
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-gray-500">Leaderboard feature is currently under development.</p>
        )}

        <button disabled className="mt-4 px-4 py-2 bg-gray-500 text-white rounded cursor-not-allowed">
          Not Yet Available
        </button>
        <span className="text-red-500 text-sm mt-2 block">Under Development</span>
      </div>

      {/* 收益分配说明 */}
      <div className=" shadow-md rounded-lg p-6 mt-6">
        <h2 className="text-2xl font-bold mb-4">Revenue Sharing Plan</h2>
        <p className="text-gray-700">
          All the project revenue will be periodically invested based on AI's recommendations through the Navi protocol. The profits generated from these investments will be shared between developers and donors:
        </p>
        <ul className="list-disc list-inside mt-4">
          <li className="text-gray-700">70% of the profits will be shared with top donors.</li>
          <li className="text-gray-700">30% of the profits will be allocated to project development and improvements.</li>
        </ul>
        <p className="text-sm text-gray-600 mt-4">
          Stay tuned for updates as we develop more tools and features to enhance the community's investment experience!
        </p>
      </div>
    </div>
  );
};

export default DonationsPage;
